### PR TITLE
Implement submit before capture

### PR DESCRIPTION
**Pull request by d3ming**
In order to refresh the tags we need to submit it first
1. Add `submit_campaign` function to `placelocal.py`
2. Hook it up to `tagtester` so we can submit first before capturing/comparing
3. More unit testing for `test_placelocal.py`, now at 100% coverage for placelocal.py
4. Refactors and minor fixes here and there...

### CODE REVIEW

**Comment by d3ming** [comment]
@kliu12 @obartra @ktilcu FYI - this change is needed to verify framework changes before and after json2html.  I have a local snapshot of before which I should checkin at some point as well.

**Comment by obartra** [comment]
I'm afraid I can't help much on the python side.

In terms of the JSON I would suggest moving each test template to each own file, that way on the JSON you only store the path to those files.

**Comment by d3ming** [comment]
Yeah I'm planning to refactor the tests to its own file but as a separate item: https://github.com/paperg/tagcompare/issues/58

**Comment by d3ming** [comment]
Merging this since I've used this revision to test the latest tags already and it works great

**Pull request merged**
